FROM messense/rust-musl-cross:aarch64-musl
COPY openssl-1.1.1t.tar.gz openssl-1.1.1t.tar.gz
RUN export CC=$TARGET_CC && \
    export C_INCLUDE_PATH=$TARGET_C_INCLUDE_PATH && \
    export AR=$TARGET_AR && \
    export RANLIB=$TARGET_RANLIB && \
    echo "Building OpenSSL" && \
    VERS=1.1.1t && \
    tar xzf openssl-$VERS.tar.gz && cd openssl-$VERS && \
    CFLAGS="-O3 -fPIC" ./Configure linux-aarch64 --prefix=$TARGET_HOME && \
    make -j$(nproc) && make install
