[workspace]
members = ["lib/api", "lib/cloud-ui", "lib/persistence", "cloud", "lib/service"]
resolver = "2"
[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
