#[targetrget.x86_64-unknown-linux-musl]
#rustflags = ["-C", "linker-flavor=gcc", "-C", "link-self-contained=no"]
#linker = "./musl-zcxx"
#[target.'cfg(target_os = "linux")']
#[target.x86_64-unknown-linux-gnu]
#rustflags = ["-C", "target-feature=+crt-static",
#    "-L", "native=/usr/lib/x86_64-linux-gnu/",
#    "-l", "static=fuse3",
#    "-l", "static=ssl",
#    "-l", "static=crypto"
#]
##, "-l", "static=sqlite3"
#[target.aarch64-unknown-linux-gnu]
#rustflags = ["-C", "target-feature=+crt-static",
#    "-L", "native=/usr/lib/aarch64-linux-gnu/",
#    "-l", "static=fuse3",
#    "-l", "static=ssl",
#    "-l", "static=m",
#    "-l", "static=crypto"
#]
###, "-l", "static=sqlite3"
### rustflags = [ "-C", "target-feature=+crt-static", "-C", "strip=symbols"]
#[target.aarch64-apple-darwin]
#rustflags = ["-C", "target-cpu=native"]
#
#
