[source.crates-io]
replace-with = "rsproxy"

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[registries]
[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"
#[target.x86_64-pc-windows-gnu]
#linker ="E:/msys64/usr/bin/gcc.exe"
[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "linker-flavor=gcc", "-C", "link-self-contained=no"]
linker = "./musl-zcxx"
#[target.'cfg(target_os = "linux")']
#rustflags = ["-L", "native=/usr/lib/aarch64-linux-gnu/",
#    "-l", "static=sqlite3",
#    "-l", "static=fuse3",
#    "-l", "static=ssl",
#    "-l", "static=m",
#    "-l", "static=crypto"
#]
##, "-l", "static=sqlite3"
## rustflags = [ "-C", "target-feature=+crt-static", "-C", "strip=symbols"]
